In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,6,7,8,9,0]) 
print(array)

[1 2 3 6 7 8 9 0]


In [3]:
array2= np.array([11,12,13,14,15,20,25,30])
print(array2.shape) 

(8,)


In [4]:
a = array2.reshape(2,4) 
print(a)

[[11 12 13 14]
 [15 20 25 30]]


In [5]:
print("shape: ",a.shape) 
print("dimension: ",a.ndim) 
print("data type: ",a.dtype.name) #
print("size: ",a.size) 
print("type",type(a))  

shape:  (2, 4)
dimension:  2
data type:  int64
size:  8
type <class 'numpy.ndarray'>


In [6]:
array3= np.array([[11,12],[13,14],[15,20],[25,30]]) 

In [7]:
print(array3) 

[[11 12]
 [13 14]
 [15 20]
 [25 30]]


In [8]:
print(array3.shape) 

(4, 2)


In [9]:
zeros= np.zeros((3,4))

In [10]:
zeros[0,0]=3
print(zeros)

[[3. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
np.zeros((2,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.empty((3,3)) 

array([[ 3.45126646e-31, -6.90253292e-31,  1.72563323e-31],
       [-6.90253292e-31,  1.50130091e-30, -4.65920972e-31],
       [ 1.72563323e-31, -4.65920972e-31,  2.67473151e-31]])

In [13]:
np.arange(0,12,2) 

array([ 0,  2,  4,  6,  8, 10])

In [14]:
a= np.linspace(0,1,100) 
print(a)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

In [15]:
a= np.array([1,2])
b= np.array([4,5]) 
print(a+b)
print(a-b) 
print(a**3) 

[5 7]
[-3 -3]
[1 8]


In [16]:
a= np.array([0,2,4,6,8])

In [17]:
liste = [0,2,4]
array = np.array([6,8])
print(liste)
print(array)

[0, 2, 4]
[6 8]


In [18]:
array = np.array(liste)
print(array)

[0 2 4]


In [19]:
liste2 = list(array)
print(liste2)

[0, 2, 4]


In [20]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [21]:
b=a
c=a
b[0]=5 
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [22]:
d = a.copy()

In [23]:
a= np.array([0,2,4,6,8])
print(a)

[0 2 4 6 8]


In [24]:
print(a[0])

0


In [25]:
print(a[1:2])

[2]


In [26]:
reverse_array = a[::-1]
print(reverse_array)

[8 6 4 2 0]


In [27]:
b = np.array([[0,2,4,6,8],[10,12,14,16,18]]) 
print(b)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [28]:
print(b[1,1])
print(b[:,1])
print(b[1,:])
print(b[1,1:4])
print(b[-1,:])
print(b[:,-1])

12
[ 2 12]
[10 12 14 16 18]
[12 14 16]
[10 12 14 16 18]
[ 8 18]


In [29]:
array = np.array([[0,2,4],[6,8,10],[12,14,16]])
print(array)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [30]:
a = array.ravel()
print(a)

[ 0  2  4  6  8 10 12 14 16]


In [31]:
array2 = a.reshape(3,3) 
print(array2)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [32]:
array_transpose = array2.T 
print(array_transpose)

[[ 0  6 12]
 [ 2  8 14]
 [ 4 10 16]]


In [33]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [34]:
array3.resize((2,3)) 
print(array3)

[[1 2 3]
 [4 5 6]]
